quarkus:
  http:
    port: 8081
  datasource:
    password: vno@user-2025
    jdbc:
      url: jdbc:postgresql://localhost:5432/vno_users
    username: vno_user_2025
  smallrye-jwt:
    sign:
      key: 7nVyLZkIFSXx7e1t96VK3MVaGdqjaCqqIlvJ1kA1vdJ
      algorithm: HS256
mp:
  jwt:
    verify:
      issuer: https://example.com/issuer
